export const meats = [
    'Tuna',
    'Salmon',
    'Octopus',
    'Scallop',
    'Squid',
    'Cod',
    'Clam',
    'Chicken Thigh',
    'Chicken Drumstick',
    'Crab',
    'Fish Head',
    'White Fish',
    'Turkey Breast',
    'Turkey Drumstick',
    'Tofu',
    'Pork Ribs',
    'Pork Shoulder',
    'Pork Belly',
    'Pork Chop',
    'Duck Breast',
    'Steak',
    'Beef Brisket',
    'Lamb Shanks',
    'Shrimp',
    'Prawns',
    'Rabbit',
    'Paneer',
    'Pigeon',
    'Quail',
    'Goose',
    'Whole chicken',
    'Venison',
];

export const vegetables = [
    'Cauliflower',
    'Egg Plant',
    'Leeks',
    'Sweet Potato',
    'Butternut Squash',
    'Shallots',
    'Bok Choy',
    'Cherry Tomato',
    'Cactus',
    'Crimini Mushroom',
    'Portobello Mushroom',
    'Okra',
    'Kale',
    'Brussel Sprouts',
    'String beans',
    'Radish',
    'Broccoli',
    'Potato',
    'Tomato'
];

export const sides = [
    'Red Wine',
    'Avocado',
    'Corn tortillas',
    'Mozarella',
    'Pickles',
    'Wasabi',
    'Gochujang',
    'Trail Mix',
    'Basil',
    'Cashews',
    'Dried cherries',
    'Chocolate covered Espresso beans',
    'Applesauce',
    'Chips',
    'Orange',
    'Peaches',
    'Old Bay Seasoning',
    'Prosciutto',
    'Salted egg',
    'Cheese',
    'Kimchi',
    'Chickpeas'
];
